In [ ]:
#1.create a constant array
import numpy as np

x=np.full((2,2),7,float)
x


array([[7., 7.],
       [7., 7.]])

In [ ]:
#2.generating random number
x=np.random.rand(2,2)
x

array([[0.66563966, 0.79489145],
       [0.96103657, 0.61473751]])

In [ ]:
# 3.array from 10 to 50
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [30]:
print("the array :\n", arr)
print('\n Number of elements',len(arr))
print('\n Shape of the array: ',arr.shape)
print('\n Dimension: ',arr.ndim)
print('\n Data type : ',type(arr))

the array :
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 Number of elements 40

 Shape of the array:  (40,)

 Dimension:  1

 Data type :  <class 'numpy.ndarray'>


In [39]:
#4.
#1D array of 10 zeros
z= np.zeros(10)
#3X3 array of ones
a=np.ones([3,3],int)
#4X4 identity matrix
y=np.eye(4,4)
#array from 5 to 50 with step size of 5
x=np.arange(5,50,5)
print("1D array of 10 zeros: ",z)
print('\n3X3 array of ones: \n',a)
print('\n4X4 identity matrix: \n', y)
print('\nArray from 5 to 50 with step size of 5: ',x)

1D array of 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

3X3 array of ones: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

4X4 identity matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array from 5 to 50 with step size of 5:  [ 5 10 15 20 25 30 35 40 45]


In [51]:
#5.array from 1 to 24
arr=np.arange(1,25)
print('Array from 1 to 24: \n', arr)
x=arr.reshape(4,6)

print('\nreshaped into 4X6 array :\n',arr.reshape(4,6))
print(x.shape)
print('\nreshaped into 6X4 array :\n',arr.reshape(6,4))
y=arr.reshape(6,4)
print(y.shape)
print('\nreshaped into 2X3X4 array :\n',arr.reshape(2,3,4))
z=arr.reshape(2,3,4)
print(z.shape)

Array from 1 to 24: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

reshaped into 4X6 array :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)

reshaped into 6X4 array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
(6, 4)

reshaped into 2X3X4 array :
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [54]:
#6.
a=np.array([78,85,92,67,88,73,95,81])
print("First element :\n",a[0])
print("Last element :\n",a[-1])
print('First 4 elements: \n', a[:4])
print('Last 3 elements: \n', a[-3:])

First element :
 78
Last element :
 81
First 4 elements: 
 [78 85 92 67]
Last 3 elements: 
 [73 95 81]


In [56]:
#7
a= np.array([10,20,30,40,50])
b=np.array([5,10,15,20,25])
print('a+b :\n', a+b)
print('a-b :\n', a-b)
print('a*b :\n', a*b)
print('a/b :\n', a/b)
print('Square of each element in a \n', a**2)

a+b :
 [15 30 45 60 75]
a-b :
 [ 5 10 15 20 25]
a*b :
 [  50  200  450  800 1250]
a/b :
 [2. 2. 2. 2. 2.]
Square of each element in a 
 [ 100  400  900 1600 2500]


In [63]:
#8
sal = np.array([25000,32000,28000,45000,50000,38000,42000,30000])

print('Total salary: \n', sal.sum())
print('Average salary: \n', sal.mean())
print('Total salary: \n', sal.sum())
print('Highest salary: \n', sal.max())
print('Lowest salary: \n', sal.min())
print('Median salary: \n', np.median(sal))
print('Standard deviation: \n', sal.std())


Total salary: 
 290000
Average salary: 
 36250.0
Total salary: 
 290000
Highest salary: 
 50000
Lowest salary: 
 25000
Median salary: 
 35000.0
Standard deviation: 
 8317.902379807063


In [71]:
#9
marks = np.array([45,78,89,32,67,90,55,76,41,84])
print("Score greater than 75 : ",marks[marks>75])
print("\n Score between 50 and 80: ", marks[(marks>50) & (marks<80)])
print('\n Number of students who scored less than 50: ',len(marks[marks<50]))
p=(len(marks[marks>60])/len(marks))*100
print('\n Percentage of students who scored 60 or above :', p)

Score greater than 75 :  [78 89 90 76 84]

 Score between 50 and 80:  [78 67 55 76]

 Number of students who scored less than 50:  3

 Percentage of students who scored 60 or above : 60.0


In [ ]:
marks = np.array([
    [80,75, 90],
    [65,70,72],
    [88,92,85],
    [55,60,58]
])

print("Total of Student 1 : ", marks[0].sum())
print("Total of Student 2 : ", marks[1].sum())
print("Total of Student 3 : ", marks[2].sum())
print("Total of Student 4 : ", marks[3].sum())

print("Average marks  of Student 1 : ", marks[0].mean())
print("Average marks  of Student 2 : ", marks[1].mean())
print("Average marks  of Student 3 : ", marks[2].mean())
print("Average marks  of Student 4 : ", marks[3].mean())

print("Average in subject 1 : ", np.mean(marks, axis =0))


Total of Student 1 :  245
Total of Student 2 :  207
Total of Student 3 :  265
Total of Student 4 :  173
Average marks  of Student 1 :  81.66666666666667
Average marks  of Student 2 :  69.0
Average marks  of Student 3 :  88.33333333333333
Average marks  of Student 4 :  57.666666666666664
Average in subject 1 :  [81.66666667 69.         88.33333333 57.66666667]
